repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --args= --lockfile=false --indent 3 --sort-by required
